== https://oracleus.activeevents.com/connect/sessionDetail.ww?SESSION_ID=5458[CON5458 - Today’s Rapid Java EE Development: Live Coding from Scratch to Deployment]

=== Resources

* http://www.rvl.io/alrubinger/javaone-2012-con5458[Slides]
* http://exitcondition.alrubinger.com/2012/10/01/con5458/[Companion Blog]

@ALRubinger
@aslakknutsen

Monday, Oct 1, 2012, 8:30 AM - 9:30 AM - Parc 55 - Cyril Magnin II/III

The myth of Java EE as a cumbersome platform is easily dispelled in this session, which aims to create a working application, from a blank repository to a live cloud deployment, in real time. It:

* Covers tools that bootstrap project creation, freeing you from mucking around with Maven POM boilerplate
* Generates a domain model and reverse-engineers JPA entities from it
* Automatically creates the scaffolding for tests that run in a real Java EE container, launched from the IDE
* Pushes it all to production on a public site

Using a variety of projects from the JBoss Community adhering to and building upon open standards, this presentation can create real enterprise apps in the time it takes other sessions to click through some slides. Let’s get building!


